### PR TITLE
Added support for Windows Store apps by including the OpenOrSHowAppBasedOnAppModelUserID(AppName, AppModelUserID) function

### PR DESCRIPTION
**Pull request by rickstaa**
I just incorporated your scripts into my AHK workflow. I, however, noticed that the functions were not able to load my Windows Store apps. I, therefore, added my Windows Store app load function to your repository.

### CODE REVIEW

**Comment by JuanmaMenendez** [comment]
Great contribution @rickstaa  !!

I will merge it and work on it in order to:

- Be able to **reactivate** the Windows Store app (if it is minimized)
- Eliminate the need to use the title in the hotkey configuration

**Comment by rickstaa** [comment]
Ah, that would be very nice features indeed @JuanmaMenendez and I think you might be right about the title being redundant. Let me know if you need any help. 

**Some explanations about my code**
-  I used the run command to maximise the windows store apps since during testing I noticed that for some apps the normal WinActivate command didn't work. 

**Some known problems with my code**
- I noticed that the script doesn't work correctly with the *Windows Sticky Notes* app. It does open and maximize the Sticky notes window, but it doesn't minimize it. I looked into this, and it looks to me that the developers set the active state to be always 0x0 by design. For me, this is not much of a problem since I use a third party plugin for my sticky notes but other users might run into problems so we might need to fix this or mention it in the README.

**Comment by rickstaa** [comment]
I am no longer a collaborator because I accidentally deleted my fork. Feel free to add me again if you want to.

**Comment by JuanmaMenendez** [comment]
Hi @rickstaa,

I already added the "Reactivate window" feature to your Open | Show Windows Store App function. 
I also refactored a little bit the comments, some var names, the Readme.md etc... 

Feel free to take a look and give your opinion.

Thanks again for your help ;)

**Comment by rickstaa** [comment]
O WindowActivateBottom does the trick, nice! I am unsure if #WinActivateForce is even needed now. But it doesn't hurt either. Thanks again for improving the code I posted on the forum everything looks very clean now :).

**Pull request merged**
